//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverBackup) DeepCopyInto(out *DataMoverBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverBackup.
func (in *DataMoverBackup) DeepCopy() *DataMoverBackup {
	if in == nil {
		return nil
	}
	out := new(DataMoverBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataMoverBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverBackupList) DeepCopyInto(out *DataMoverBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataMoverBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverBackupList.
func (in *DataMoverBackupList) DeepCopy() *DataMoverBackupList {
	if in == nil {
		return nil
	}
	out := new(DataMoverBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataMoverBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverBackupSpec) DeepCopyInto(out *DataMoverBackupSpec) {
	*out = *in
	out.VolumeSnapshotContent = in.VolumeSnapshotContent
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverBackupSpec.
func (in *DataMoverBackupSpec) DeepCopy() *DataMoverBackupSpec {
	if in == nil {
		return nil
	}
	out := new(DataMoverBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverBackupStatus) DeepCopyInto(out *DataMoverBackupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverBackupStatus.
func (in *DataMoverBackupStatus) DeepCopy() *DataMoverBackupStatus {
	if in == nil {
		return nil
	}
	out := new(DataMoverBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverRestore) DeepCopyInto(out *DataMoverRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverRestore.
func (in *DataMoverRestore) DeepCopy() *DataMoverRestore {
	if in == nil {
		return nil
	}
	out := new(DataMoverRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataMoverRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverRestoreList) DeepCopyInto(out *DataMoverRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataMoverRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverRestoreList.
func (in *DataMoverRestoreList) DeepCopy() *DataMoverRestoreList {
	if in == nil {
		return nil
	}
	out := new(DataMoverRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataMoverRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverRestoreSpec) DeepCopyInto(out *DataMoverRestoreSpec) {
	*out = *in
	out.ResticSecretRef = in.ResticSecretRef
	out.DestinationClaimRef = in.DestinationClaimRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverRestoreSpec.
func (in *DataMoverRestoreSpec) DeepCopy() *DataMoverRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(DataMoverRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverRestoreStatus) DeepCopyInto(out *DataMoverRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverRestoreStatus.
func (in *DataMoverRestoreStatus) DeepCopy() *DataMoverRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(DataMoverRestoreStatus)
	in.DeepCopyInto(out)
	return out
}
